[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
subscription_processor = "9hcxbmQq18uCcSTs9zMKAHivEYrfJ9DF3FMn5LhgD3n8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
